version: '3.7'
services:
    app:
        container_name: monitoria-jte-01
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '3305:3000'
        environment:
            - CHOKIDAR_USEPOLLING=true