name: Node.js CI

on:
  push:
    branches:
      - "**"             # Push in all branchs 
  pull_request:
    branches: [ Frontend ]

jobs:
  frontend:
    runs-on: ubuntu-latest

    env:
      github-token: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: install Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          
      - run: yarn 
        working-directory: ./frontend

      - run: yarn test
        working-directory: ./frontend

      - run: yarn test --coverage
        working-directory: ./frontend
      
      # - name: deployFront
      # - run: cp ./frontend/* ./
      # - run: ls -la